name: CI

on:
  pull_request:
    types: [opened, reopenned, ready_for_review, edited, synchronize]
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.16.0]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('package-lock.json') }}
      
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git fetch --no-tags --prune --depth=5 origin main
      
      - name: Install deps
        if: steps.cache-node-modules.cache-hit != 'true'
        run: npm install

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          architecture: x64
      - run: flutter --version

  analyze:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('package-lock.json') }}
        
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'